// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";
import * as Button from "./Button.bs.js";

function s(prim) {
  return prim;
}

function NewBlock(Props) {
  var post = Props.post;
  var restoreHandle = Props.restoreHandle;
  var deleteHandle = Props.deleteHandle;
  return React.createElement("div", {
              className: "relative bg-yellow-100 px-8 py-4 mb-4 h-40"
            }, React.createElement("p", {
                  className: "text-center white mb-1"
                }, "This post from " + Post.title(post) + " by " + Post.author(post) + " will be permanently removed in 10 seconds."), React.createElement("div", {
                  className: "flex justify-center"
                }, React.createElement(Button.make, {
                      text: "Restore",
                      className: "mr-4 mt-4 bg-yellow-500 hover:bg-yellow-900 text-white py-2 px-4",
                      handleClick: restoreHandle
                    }), React.createElement(Button.make, {
                      text: "Delete Immediately",
                      className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4",
                      handleClick: deleteHandle
                    })), React.createElement("div", {
                  className: "bg-red-500 h-2 w-full absolute top-0 left-0 progress"
                }));
}

var make = NewBlock;

export {
  s ,
  make ,
  
}
/* Post Not a pure module */
